services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - pgdata_v3:/var/lib/postgresql/data   # <- volumen NUEVO para reinit limpio
    networks:
      backend_net:
        aliases: [postgres]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile   # <- usa la ruta real
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    # sin env_file aquí
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      GUNICORN_WORKERS: "3"
      GUNICORN_THREADS: "1"
      GUNICORN_TIMEOUT: "120"
      DB_MAX_RETRIES: "30"
      DB_RETRY_DELAY: "1"
    networks:
      backend_net:
        aliases: [backend]
    ports:
      - "8001:8000"
    volumes:
      - media:/app/media
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/admin/login/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata_v3:
    name: pgdata_v3
  media:
    name: backend_media

networks:
  backend_net:
    driver: bridge
