# Generated by Django 5.2.7 on 2025-10-17 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                ("excerpt", models.TextField(verbose_name="Resumen")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                ("image", models.URLField(verbose_name="Imagen")),
                ("thumb", models.URLField(verbose_name="Miniatura")),
                (
                    "imageAlt",
                    models.CharField(max_length=255, verbose_name="Texto alternativo"),
                ),
                ("author", models.CharField(max_length=255, verbose_name="Autor")),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="posts", to="blog.tag", verbose_name="Etiquetas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
