# Generated by Django 5.2.7 on 2025-10-20 21:06

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models
from django.db.migrations.operations.models import ModelOperation


class AlterModelBases(ModelOperation):
    """Custom operation to adjust the base classes of a model in state."""

    reduces_to_sql = False
    serialization_expand_args = ["name", "bases", "old_bases"]

    def __init__(self, name, bases, old_bases):
        self.name = name
        self.bases = bases
        self.old_bases = old_bases

    def state_forwards(self, app_label, state):
        key = (app_label, self.name.lower())
        model_state = state.models[key].clone()
        model_state.bases = self.bases
        state.models[key] = model_state

    def state_backwards(self, app_label, state):
        key = (app_label, self.name.lower())
        model_state = state.models[key].clone()
        model_state.bases = self.old_bases
        state.models[key] = model_state

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # No database operation required; only the model state changes.
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def describe(self):
        return f"Alter bases for {self.name}"


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_reaction"),
    ]

    operations = [
        AlterModelBases(
            name="category",
            bases=(parler.models.TranslatableModel,),
            old_bases=(models.Model,),
        ),
        AlterModelBases(
            name="tag",
            bases=(parler.models.TranslatableModel,),
            old_bases=(models.Model,),
        ),
        AlterModelBases(
            name="post",
            bases=(parler.models.TranslatableModel,),
            old_bases=(models.Model,),
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="legacy_name",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="slug",
            new_name="legacy_slug",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="description",
            new_name="legacy_description",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="legacy_name",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="legacy_title",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="slug",
            new_name="legacy_slug",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="excerpt",
            new_name="legacy_excerpt",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="legacy_content",
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=160, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Categoría Translation",
                "db_table": "blog_category_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PostTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
                ),
                ("excerpt", models.TextField(verbose_name="Resumen")),
                ("content", models.TextField(verbose_name="Contenido")),
            ],
            options={
                "verbose_name": "Entrada Translation",
                "db_table": "blog_post_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TagTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=120, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "Etiqueta Translation",
                "db_table": "blog_tag_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["translations__name"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["translations__name"],
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
            },
        ),
        migrations.RenameIndex(
            model_name="reaction",
            new_name="blog_reacti_content_3b2361_idx",
            old_name="blog_react_content_8f27e5_idx",
        ),
        migrations.RenameIndex(
            model_name="reaction",
            new_name="blog_reacti_user_id_b9b50e_idx",
            old_name="blog_react_user_co_3f2b9e_idx",
        ),
        migrations.AddField(
            model_name="categorytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="posttranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="blog.post",
            ),
        ),
        migrations.AddField(
            model_name="tagtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="blog.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categorytranslation",
            unique_together={
                ("language_code", "master"),
                ("language_code", "slug"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="posttranslation",
            unique_together={
                ("language_code", "master"),
                ("language_code", "slug"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="tagtranslation",
            unique_together={
                ("language_code", "master"),
                ("language_code", "slug"),
            },
        ),
        migrations.AddIndex(
            model_name="categorytranslation",
            index=models.Index(
                fields=["language_code", "name"],
                name="category_lang_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="posttranslation",
            index=models.Index(
                fields=["language_code", "title"],
                name="post_lang_title_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tagtranslation",
            index=models.Index(
                fields=["language_code", "name"],
                name="tag_lang_name_idx",
            ),
        ),
    ]
