# Generated by Django 5.2.7 on 2025-10-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_parler_data_migration"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="categorytranslation",
            name="category_lang_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="posttranslation",
            name="post_lang_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="tagtranslation",
            name="tag_lang_name_idx",
        ),
        migrations.AlterUniqueTogether(
            name="categorytranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AlterUniqueTogether(
            name="posttranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AlterUniqueTogether(
            name="tagtranslation",
            unique_together={("language_code", "master")},
        ),
    ]
