# Generated by Django 5.2.7 on 2025-10-22 09:23

from django.db import migrations


def create_custom_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    mapping = {
        "post": [
            ("can_approve_post", "Puede aprobar publicaciones"),
            ("can_publish_post", "Puede publicar publicaciones"),
        ],
        "comment": [
            ("can_moderate_comment", "Puede moderar comentarios"),
        ],
    }

    for model_name, permissions in mapping.items():
        content_type, _created = ContentType.objects.get_or_create(
            app_label="blog", model=model_name
        )
        for codename, name in permissions:
            Permission.objects.update_or_create(
                content_type=content_type,
                codename=codename,
                defaults={"name": name},
            )


def noop(apps, schema_editor):
    """Reverse operation placeholder."""



class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rbac_audit_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [("can_moderate_comment", "Puede moderar comentarios")],
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-date", "-id"],
                "permissions": [
                    ("can_approve_post", "Puede aprobar publicaciones"),
                    ("can_publish_post", "Puede publicar publicaciones"),
                ],
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
            },
        ),
        migrations.RunPython(create_custom_permissions, noop),
    ]
